### ISSUE TITLE
ERROR: UndefVarError: warn not defined

### ISSUE THREAD

**Issue by schneiderfelipe** [JuliaMatrices/LowRankApprox.jl#30] opened 2021-01-26 23:26 UTC
Hi, I'm getting an error when trying the first example in the README.md. Here's an MWE:

```julia
julia> using LowRankApprox

julia> n = 1024
1024

julia> A = matrixlib(:hilb, n, n);

julia> F = pqrfact(A);

julia> aerr = snormdiff(A, F)
ERROR: UndefVarError: warn not defined
Stacktrace:
 [1] snorm(::LinearOperator{Float64}, ::LRAOptions; args::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/schneider/.julia/packages/LowRankApprox/LmABb/src/snorm.jl:26
 [2] snorm at /home/schneider/.julia/packages/LowRankApprox/LmABb/src/snorm.jl:15 [inlined] (repeats 2 times)
 [3] #snormdiff#40 at /home/schneider/.julia/packages/LowRankApprox/LmABb/src/snorm.jl:48 [inlined]
 [4] snormdiff at /home/schneider/.julia/packages/LowRankApprox/LmABb/src/snorm.jl:48 [inlined]
 [5] snormdiff(::Array{Float64,2}, ::PartialQR{Float64}; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/schneider/.julia/packages/LowRankApprox/LmABb/src/snorm.jl:50
 [6] snormdiff(::Array{Float64,2}, ::PartialQR{Float64}) at /home/schneider/.julia/packages/LowRankApprox/LmABb/src/snorm.jl:50
 [7] top-level scope at REPL[71]:1

julia> versioninfo()
Julia Version 1.4.1
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD Ryzen 5 1600 Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, znver1)
```

**Comment by klho** [comment] 2021-04-20 05:33
Duplicate of #18; should be fixed by 9da3a79.

**Closed as completed by klho** 2021-04-20 05:33 UTC
